### ISSUE TITLE
"npm install brickpi-raspberry" fails

### ISSUE THREAD

**Issue by bskendig** [lmclupr/brickpi-nodejs#1]
On my Raspberry Pi with BrickPi, this command:

`npm install brickpi-raspberry`

fails:

```
$ npm install brickpi-raspberry
npm http GET https://registry.npmjs.org/brickpi-raspberry

npm ERR! Error: failed to fetch from registry: brickpi-raspberry
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "brickpi-raspberry"
npm ERR! cwd /home/pi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: brickpi-raspberry
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm not ok
```

**Comment by lmclupr** [comment]
Brian,

Sorry. I have no idea what's wrong.

**Comment by bskendig** [comment]
According to https://gist.github.com/justinjenkins/16adc15338bb265f6808, looks like this was a problem with the very old version of npm (and node) that are in Raspbian wheezy.

I upgraded to npm 2.14.12 / node 4.3.2 (ARMv7), and now the installation begins, but very quickly runs into errors. Before I go into details, would you please let me know what versions of npm and node you have brickpi-raspberry working with?

**Comment by bskendig** [comment]
Here's the beginning of the errors I get:

```
$ npm install brickpi-raspberry
\
> serialport@1.6.3 install /home/pi/node_modules/brickpi-raspberry/node_modules/serialport
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from /home/pi/.node-gyp/4.3.2/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
/home/pi/.node-gyp/4.3.2/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/4.3.2/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/pi/.node-gyp/4.3.2/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
In file included from ../node_modules/nan/nan.h:80:0,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
../node_modules/nan/nan_new.h:23:43: error: template declaration of ‘v8::Local<T> NanIntern::To’
../node_modules/nan/nan_new.h:23:39: error: ‘Handle’ is not a member of ‘v8’
../node_modules/nan/nan_new.h:23:61: error: expected primary-expression before ‘>’ token
../node_modules/nan/nan_new.h:23:63: error: ‘i’ was not declared in this scope
```

and then, a few hundred lines later,

```
serialport.target.mk:90: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/src/node-v4.3.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "/usr/local/src/node-v4.3.2-linux-armv7l/bin/node" "/usr/local/src/node-v4.3.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=serialport" "--configuration=Release" "--module_name=serialport" "--version=1.6.3" "--major=1" "--minor=6" "--patch=3" "--runtime=node" "--node_abi=node-v46" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=./serialport" "--host=https://node-serialport.s3.amazonaws.com/" "--module_path=/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/build/serialport/v1.6.3/Release/node-v46-linux-arm" "--remote_path=./serialport/v1.6.3/Release/" "--package_name=node-v46-linux-arm.tar.gz" "--staged_tarball=build/stage/serialport/v1.6.3/Release/node-v46-linux-arm.tar.gz" "--hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/" "--hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v46-linux-arm.tar.gz"
gyp ERR! cwd /home/pi/node_modules/brickpi-raspberry/node_modules/serialport
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/src/node-v4.3.2-linux-armv7l/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.3 --major=1 --minor=6 --patch=3 --runtime=node --node_abi=node-v46 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/build/serialport/v1.6.3/Release/node-v46-linux-arm --remote_path=./serialport/v1.6.3/Release/ --package_name=node-v46-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.6.3/Release/node-v46-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v46-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.1.13-v7+
node-pre-gyp ERR! command "/usr/local/src/node-v4.3.2-linux-armv7l/bin/node" "/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/node_modules/brickpi-raspberry/node_modules/serialport
node-pre-gyp ERR! node -v v4.3.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/src/node-v4.3.2-linux-armv7l/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.3 --major=1 --minor=6 --patch=3 --runtime=node --node_abi=node-v46 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/home/pi/node_modules/brickpi-raspberry/node_modules/serialport/build/serialport/v1.6.3/Release/node-v46-linux-arm --remote_path=./serialport/v1.6.3/Release/ --package_name=node-v46-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.6.3/Release/node-v46-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v46-linux-arm.tar.gz' (1)
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/src/node-v4.3.2-linux-armv7l/bin/node" "/usr/local/bin/npm" "install" "brickpi-raspberry"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.6.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.6.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```

/home/pi/npm-debug.log is 1756 lines long, so I won't paste the whole thing here unless it would help.

**Comment by lmclupr** [comment]
Brian,

I don't have the environment installed anymore, but from memory, I had used
raspian distribution from Dexter, then had downloaded the latest node and
npm source and compiled them on the rpi.  But let me reinstall the whole
thing and I will try to debug it.  I may be calling a (now) deprecated
version of seriaport

**Comment by bskendig** [comment]
Thank you, I appreciate the help! Looking forward to coding robotics in Node.

**Comment by lmclupr** [comment]
Brian,

You'll have to give me a bit more time on this.  I realize that I don't 
have much left of the original environment, i.e. I am even missing an SD 
card to use for this.  Please be patient, I'll get to it.

/Luc

**Comment by bskendig** [comment]
I am patient! Thank you for your effort!

**Comment by DennisTheD** [comment]
Had the same issue. Updating node fixed it. Take a look at: http://stackoverflow.com/questions/12913141/message-failed-to-fetch-from-registry-while-trying-to-install-any-module

**Comment by lmclupr** [comment]
Thank you so very much for this info.

/Luc

**Comment by bskendig** [comment]
@schweinegrippe94 - so you're saying you were able to get brickpi-raspberry and serialport both installed on your Pi? What versions of nodejs and npm did you get them to work with?

**Comment by DennisTheD** [comment]
Sorry, but I´m unable to check this. I had to give back the Hardware to my University. But i guess it was the current release, installed by the install script.

**Comment by bskendig** [comment]
I wasn't able to get this to work with the current release a few weeks ago (npm 2.14.12 / node 4.3.2 ARMv7), so I'm still eager for news from @lmclupr about how to get it to work.

**Comment by WayneKennedy** [comment]
I've been trying all day to get this to work on the latest Raspbian from raspberrypi.org, and getting the same error around Serialport failing to install. Just built an SD card from the DEXTER latest image, and boom, it worked first time! So something in the October '16 Dexter image helps the install to work. Just FYI.

**Comment by lmclupr** [comment]
You need the dexter image for it to work.  Its tuned somehow for this.
Hope you enjoy the module.

Luc

**Comment by codeofsumit** [comment]
@WayneKennedy I do have the same problem and I have the dexter industries image.

This is what I get when I type `dex` into the browser.
![image](https://cloud.githubusercontent.com/assets/2399810/23832029/4ad63654-072d-11e7-8945-e712f82de050.png)

This is what is in the file "version" on the Pi's desktop:
![image](https://cloud.githubusercontent.com/assets/2399810/23832051/c31881ee-072d-11e7-9c8e-dd6f15ad9c86.png)


I can install all other npm dependencies but install of brickpi-raspberry fails

```
npm ERR! serialport@1.6.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@1.6.3 install script 'node-pre-gyp install --fallback-to-build'.
```

**Comment by codeofsumit** [comment]
I just went through the Dexter Update process for BrickPi3 and "Dexterind Software" and I still get this error.

**Comment by codeofsumit** [comment]
Made it work. Had to install an older version of serialport (2.1.2) manually, updating the dependency for this lib in the package.json and then it worked.
However I'm not able to control any motors. Get a timeout on `.setup()` :(
