### ISSUE TITLE
Does this work with the Brickpi3?

### ISSUE THREAD

**Issue by ppinto** [lmclupr/brickpi-nodejs#5]
I tried setting this up on a brickpi3, and a brickpi seems to work on the brickpi but get's this error on the brickpi3

root@dpcbot03:~/jscode# node bot1.js
rx Timeout

Error: timed out
    at null.<anonymous> (/root/node_modules/brickpi-raspberry/Brickpi.js:46:18)
    at /root/node_modules/brickpi-raspberry/Driver.js:36:6
    at /root/node_modules/brickpi-raspberry/node_modules/async/lib/async.js:151:21
    at null._onTimeout (/root/node_modules/brickpi-raspberry/Driver.js:52:2)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

here's the code
var brickpi = require('brickpi-raspberry');
.
var robot = new brickpi.BrickPi();
var motorA = new brickpi.Motor({port: brickpi.PORTS.MA, name: 'motorA'});
var motorB = new brickpi.Motor({port: brickpi.PORTS.MB, name: 'motorB'});
.
robot.addMotor(motorA).addMotor(motorB).setup();
.
robot.on('ready', function() {
    motorA.resetPosition();
    motorB.resetPosition();
    robot.run();
.
    motorA.start(100).moveTo(5000, function(err) {
        // called when motorA has reached 5000 ticks (2500 degrees in rotation).
    });
});
.
setTimeout(function() {
    motorB.start(50);
}, 3000);
.
setTimeout(function() {
    motorB.stop();
}, 5000);
.
setTimeout(function() {
    robot.stop();
}, 10000);
.

**Comment by juansuerogit** [comment]
i just came up this post in december.. wow no response :(  #feelingPlayed

**Comment by lmclupr** [comment]
FeelingPlayed?  What the hell does that mean?  I coded the module 2-3 years ago.  I spent about a week coding it.  Free of charge.  This is volunteering work.  And you come and you complain?  And you have never committed anything yourself?  I don't even have a BrickPi anymore let alone a Brickpi3.  Why don't you pull the code, spend a couple of days updating it for BrickPi3 and submit it.

**Comment by ppinto** [comment]
lmclupr and fogbridgegit,

I was trying to get this to work with Node Red, on a Brickpi 3.  I was able to find a workaround sending messages to Python from Node Red eliminating the need for the NodeJS interface,   After doing some research the Brickpi 3 had rewritten the entire driver interface and only provides stubs for python.   This will not work without a complete rewrite - and I do not believe they have published the interface as they have in the past. 

fogbridgegit - no reason to be snarky, this is not Youtube and people here are just trying to help.   If you want to be a maker then make -- don't break

Good luck
